# Generated by Django 5.1.6 on 2025-03-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waterdemands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="populationdata",
            name="floating_pop",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
