# Generated by Django 5.1.6 on 2025-03-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RasterVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organisations", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("file_location", models.FileField(upload_to="rasters/")),
            ],
        ),
    ]
