# Generated by Django 5.1.6 on 2025-03-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subdistrict",
            name="district_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subdistrict",
            name="subdistrict_name",
            field=models.CharField(max_length=100),
        ),
    ]
