# Generated by Django 5.1.6 on 2025-03-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stp", "0002_alter_subdistrict_district_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="village",
            old_name="number_of_asi_sites",
            new_name="Subdistric",
        ),
        migrations.RenameField(
            model_name="village",
            old_name="number_of_tourists",
            new_name="population",
        ),
        migrations.RemoveField(
            model_name="village",
            name="gdp_at_current_prices",
        ),
        migrations.RemoveField(
            model_name="village",
            name="mean_rainfall",
        ),
        migrations.RemoveField(
            model_name="village",
            name="mean_temperature",
        ),
        migrations.RemoveField(
            model_name="village",
            name="sewage_gap",
        ),
        migrations.RemoveField(
            model_name="village",
            name="village_code",
        ),
        migrations.RemoveField(
            model_name="village",
            name="water_quality_index",
        ),
        migrations.AddField(
            model_name="village",
            name="sewage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="village",
            name="subdistrict",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
